apiVersion: v1
kind: Service
metadata:
  name: solar-system
  namespace: _{_NAMESPACE_}_
  labels:
    app: solar-system
spec:
  selector:
    app: solar-system
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP