# .github/workflows/ci-consumer.yml
name: CI Consumer - Sistema Solar

on:
  push:
    branches: [ main, 'feature/*' ]
  workflow_dispatch:

jobs:
  call-ci-base:
    uses: your-org/ci-templates/.github/workflows/ci-base.yml@main
    with:
      node-version: "18"
      image-name: "luisrg3citperuacr001.azurecr.io/sistemasolar"
      manifests-repo: "your-org/sistemasolar-manifests"
      manifests-path: "kubernetes/development"
      deploy-via-argocd: true
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      MANIFESTS_REPO_TOKEN: ${{ secrets.MANIFESTS_REPO_TOKEN }}
      ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
      ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
      ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
